### ISSUE TITLE
There is nothing being published on /odom topic

### ISSUE THREAD

**Issue by GDnsk** [EwingKang/Simple-ROS-Arduino-odometry#1]
Hello and thank you for you to share this amazing project.
The problem is that i did setup everything in my hardware but when i run the serial_odom node there is nothing reaching the topic, i did run rostopic echo /odom and all that it gave me is the structure of /odom msg with everything with 0.

Thank you.

**Comment by EwingKang** [comment]
Hello @GuilhermeDaniluski, Here's a quick check list: 

1. Did you setup the correct port ? (there should be an error if not)
2. Did you have your user add to dialout group? ( `sudo usermod -a -G dialout $USER` )
3. **Did you have a topic "encoder" (geometry_msgs::Vector3) published?** (x: left wheel/ y: right wheel, forward: >0, backward: <0)

This project currently handles only **single phase odometry** (aka tachometer), It requies addtional information to determine the direction of the wheel, e.g. motor control topic.
I've already finished a version for common quadrature-phase encoder, but I haven't combine everything yet because I'm lazy. Since you mentioned it I'll probably restart the project pretty soon.

**Comment by EwingKang** [comment]
V1.0 is reased, should be good at any type of encoders
